[pytest]
testpaths = tests
pythonpath = .
filterwarnings =
    ignore:Using .httpx. with .starlette.testclient. is deprecated
    ignore:websockets\.legacy is deprecated:DeprecationWarning
    ignore:websockets\.server\.WebSocketServerProtocol is deprecated:DeprecationWarning
